const EVENTS = {
    RUNE: {
        CONSUME: "rune_consume",
        GENERATE_START_MAP: "generate_start_rune",
        NEW_REQUEST: "new_rune_request",
        NEW_RESPONSE: "new_rune_response",
        SWAP_RUNE: "swap_rune",
        OPPONENT_SWAP_RUNE: "opponent_swap_rune",
    },
    PLAYER: {
        FIND_MATCH: "find_match",
        MATCH_FOUND: "match_found",
        CURRENT_TURN: "current_turn",
        TURN_REQUEST: "turn_request",
        TURN_RESPONSE: "turn_response",
        PICK_MONSTER: "pick_monster",
    },
    GAME: {
        GAME_START_REQUEST: "game_start_request",
        TURN_BASE_LIST_PUSH_DATA: "turn_base_list_push_data",
        TURN_BASE_LIST_REQUEST: "turn_base_list_request",
        PICK_MONSTER_POST: "pick_monster_post",
        PICK_MONSTER_PUSH: "pick_monster_push",
        PICK_MONSTER_CONFIRM_POST: "pick_monster_confirm_post",
        PICK_MONSTER_CONFIRM_PUSH: "pick_monster_confirm_push",
        END_PICK_MONSTER: "end_pick_monster",
        POINT_INIT_REQUEST: "point_init_request",
        POINT_INIT_RESPONSE: "point_init_response",
        POINT_UPDATE_POST: "point_update_post",
        POINT_UPDATE_PUSH: "point_update_push",
        TALENT_POINT_UPDATE_REQUEST: "talent_point_update_request",
        TALENT_POINT_UPDATE_RESPONSE: "talent_point_update_response",
        MONSTER_DATA_REQUEST: "monster_data_request",
        MONSTER_DATA_RESPONSE: "monster_data_response",
        SUMMON_REQUEST: "summon_request",
        SUMMON_RESPONSE: "summon_response",
    },
    MONSTER: {
        MONSTER_LIST: "monster_list",
        MONSTER_ACTION_REQUEST: "monster_action_request",
        MONSTER_ACTION_RESPONSE: "monster_action_response",
        UPDATE_EFFECT_REQUEST: "update_effect_request",
        UPDATE_EFFECT_RESPONSE: "update_effect_response",
    },
};
export default EVENTS;
